version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: proscient_postgres
    restart: always
    environment:
      POSTGRES_USER: proscient
      POSTGRES_PASSWORD: proscient_secret
      POSTGRES_DB: proscient_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
